### ISSUE TITLE
Constant selector for buttons in Feedback component

### ISSUE THREAD

**Issue by shazron** [adobe/gatsby-theme-parliament#2]
Component: https://github.com/adobe/gatsby-theme-parliament/blob/main/packages/gatsby-theme-parliament/src/components/Feedback.js

For Adobe Launch, to query select the appropriate button elements, I could use the existing nested styles to select the buttons but it would be better to use a constant selector, so we should use a fixed classname for example. Are there any issues in adding this?

**Comment by icaraps** [comment]
> we should use a fixed classname for example

mhh I don't see an issue with that...
