### ISSUE TITLE
Restart server on gatsby-config change

### ISSUE THREAD

**Issue by ashryanbeats** [adobe/gatsby-theme-parliament#20]
Can we add a watcher to restart/rebuild the server when the gatsby-config changes? 

As-is currently (while running `npm run dev`), editing gatsby-config causes the script to reload (?) the site in place, but this rarely seems to be successful. The fix is usually to stop and restart the server manually.

**Comment by icaraps** [comment]
This is fixed but it'll require a modification in how to retrieve the globalNav config see https://github.com/adobe/gatsby-theme-parliament/blob/main/example/gatsby-config.js#L13-L16
