### ISSUE TITLE
Including markdown files as fragments within another markdown file in the same repo

### ISSUE THREAD

**Issue by ashryanbeats** [adobe/gatsby-theme-parliament#23]
Is it possible to include markdown files as fragments within another markdown file in the same repo?

Example:

# File 1 (md1.md)

```
# Section 2
Here's some content that will be shown within another markdown file.
```

# File 2 (md2.md)

This is pseudocode/markdown:

```
import section2 from ./md1.md

# Section 1
Here's some content within this file.

@section2
```

**Comment by icaraps** [comment]
Yes that should be possible but I think you'll have to add the query prop so something like that:

```
import Section2 from ./md1.md

# Section 1
Here's some content within this file.

<Section2 query="all" />
```

**Comment by ashryanbeats** [comment]
Is this documented somewhere?

**Comment by icaraps** [comment]
This is missing in the docs. I'll add a section in the README about including markdown inside markdown from the same repo. Thanks !

**Comment by icaraps** [comment]
Documentated at https://github.com/adobe/gatsby-theme-parliament#embedding-markdown-documents-and-filtering-content
