### ISSUE TITLE
[Safari] Links to named anchors jump past the element containing the anchor id

### ISSUE THREAD

**Issue by ashryanbeats** [adobe/gatsby-theme-parliament#24]
# Current
Currently, if I click the "Go live" link (`/#go-live`) seen in the top nav in the screenshot below, the scroll jumps past the "Go live" heading which contains the anchor id:

![Screen Shot 2020-09-15 at 15 04 13](https://user-images.githubusercontent.com/1370591/93253481-eccefd80-f764-11ea-8f43-61d6109402a7.png)

# Desired
Preferably, we'd be able to see the heading after the scroll:

![Screen Shot 2020-09-15 at 15 04 25](https://user-images.githubusercontent.com/1370591/93253511-f8222900-f764-11ea-8376-fd546ec87695.png)

---

Note that the above is simply an example (I'm not totally sold we'll do this type of linking from top nav on the docs top page). 

However, this phenomenon is present in more legitimate use cases for named anchors as well, like the autogenerated right-hand table-of-contents in narrative content.

# Possible source of issue
My guess is that we need to account for the height taken up by the top-nav.

**Comment by icaraps** [comment]
@ashryanbeats Is this bug persistent ? Does it occur every time (also for the table-of-contents) ?

**Comment by ashryanbeats** [comment]
It is persistent. I was on 2.0.0 when I report this, but I'm also seeing it in 2.1.3.

I'm on Safari 13.1.1.

**Comment by icaraps** [comment]
Indeed I can reproduce it on Safari. 

Chrome, Firefox, Edge are all fine. I'll look into it thanks !
