### ISSUE TITLE
Increase SideNav nesting limit

### ISSUE THREAD

**Issue by icaraps** [adobe/gatsby-theme-parliament#30]
Currently it's limited to to 3 due to Spectrum's recommendation 
> The multi-level side navigation should only go 3 levels deep

This should be doubled at least or infinite ?

**Comment by icaraps** [comment]
Infinite is not supported by GraphQL (ie recursive data) thus setting the max nesting level to 6.

**Comment by icaraps** [comment]
Looks like this:

<img width="253" alt="Screen Shot 2020-09-25 at 12 53 36 PM" src="https://user-images.githubusercontent.com/6012307/94259662-1fc87c80-ff2f-11ea-864f-12fe9e5be3a3.png">

**Comment by ashryanbeats** [comment]
Can we surface this to Lise please? While the nested information is present, this doesn't _appear_ visually as nesting.
